# Identificador del proyecto
sonar.projectKey=tienda_ropa_inventario
sonar.projectName=Tienda de Ropa - Gestión de Inventario
sonar.projectVersion=1.0

# Código fuente actual de las apps
sonar.sources=apps/backend,apps/frontend
sonar.sourceEncoding=UTF-8

# URL del servidor local
sonar.host.url=http://host.docker.internal:9000
